### PR TITLE
Add Apiary Blueprint Manager to tooling list

### PR DESCRIPTION
**Pull request by Tuxilero**
Add Apiary Blueprint Manager to tooling list

### CODE REVIEW

**Comment by zdne** [comment]
:+1:

**Comment by zdne** [comment]
@Tuxilero actually, can I suggest renaming the plug-in from "Apiary Blueprint Manager" to "API Blueprint Manager" ? 

Strictly speaking it is API Blueprint, not Apiary Blueprint. However I understand the plug-in is tightly coupled with Apiary so it is maybe "Apiary API Blueprint" plug-in? :dancer:  

I know, naming is hard..

**Comment by zdne** [comment]
@Tuxilero let me know whether it makes sense.

**Comment by Tuxilero** [comment]
@zdne Yes, you are absolutely right. Unfortunately, I realized that right after receiving by bachelor thesis. So, I suggest changing it to API Blueprint Manager only here for next month, and renaming whole plugin right after completing my thesis.

**Comment by zdne** [comment]
Sounds good! Let's rename it just here.

**Pull request merged**
